### ISSUE TITLE
[Bug] Overlapping images in Intercom widget

### ISSUE THREAD

**Issue by charles-clerk-dev** [calibreapp/react-live-chat-loader#213]
### Describe the bug

The intercom chat widget loads slightly off-center from the placeholder. This cause the chat widget to be slightly visible behind the placeholder. 

### How To Reproduce

1. Go to[ https://www.clerk.dev]( https://www.clerk.dev)
2. Watch the purple chat widget visibly load behind the placeholder.

### Screenshots
<img width="129" alt="Screen Shot 2022-12-14 at 4 36 22 PM" src="https://user-images.githubusercontent.com/96198083/207738636-3ae91546-cd2a-4ebb-ba19-b4550769fa11.png">

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by benschwarz** [comment]
Hey @charles-clerk-dev, thanks for logging. Could you please confirm which version you are using?

**Comment by robmorieson** [comment]
@charles-clerk-dev — it looks like this issue is due to Intercom’s default chat widget styling having changed since the most recent release of this package. I’ll raise a PR to bring the placeholder in line with Intercom, then get a new version rolled out.

**Comment by charles-clerk-dev** [comment]
Sorry I missed your first message (we are on version 2.8.0). Thank you so much for the quick response!

**Comment by robmorieson** [comment]
@charles-clerk-dev - happy to announce this fix has been merged and released in 2.8.1; thanks again for reporting!

As a side note, I just wanted to check that you’re across the `color` prop on the `Intercom` component —  this allows you to match the colour of the _placeholder_ icon with the _real_ icon served up by Intercom. e.g. `<Intercom color="#6c47ff" />`

Closing this one off, but do let us know if you face any future issues, cheers!

**Comment by kinotto** [comment]
Hi @robmorieson i'm still experiencing this issue, i'm running v2.8.1

![image](https://user-images.githubusercontent.com/4570071/230137768-e91e6950-76bf-454d-a475-18d04ee92073.png)

**Comment by robmorieson** [comment]
@kinotto — thanks for logging.  I'm not able to replicate this issue on our [example website](https://react-live-chat-loader.vercel.app/intercom) so wondering if it could be due to custom Intercom icon styling?  Placeholder icons only match default Intercom styling (although they can be customised via a `color` prop and styled via a `live-chat-loader-placeholder` class name).

If you'd like to lodge this as a new issue we might be able to look into it further.

**Comment by kinotto** [comment]
Hi @robmorieson, thank you, there is no custom styling though, i'll open a new bug now
